# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "github-actions"
    open-pull-requests-limit: 100
    schedule:
      interval: daily
      time: "19:45"
      timezone: "Europe/Berlin"
    rebase-strategy: "auto"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "composer"
    open-pull-requests-limit: 100
    schedule:
      interval: daily
      time: "19:45"
      timezone: "Europe/Berlin"
    rebase-strategy: "auto"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "gradle"
    open-pull-requests-limit: 100
    schedule:
      interval: daily
      time: "19:45"
      timezone: "Europe/Berlin"
    rebase-strategy: "auto"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "docker"
    open-pull-requests-limit: 100
    schedule:
      interval: daily
      time: "19:45"
      timezone: "Europe/Berlin"
    rebase-strategy: "auto"

  - package-ecosystem: pip
    directory: /cucumber
    labels:
      - "pip cucumber"
    open-pull-requests-limit: 100
    schedule:
      interval: daily
      time: "19:45"
      timezone: "Europe/Berlin"
    rebase-strategy: "auto"

  - package-ecosystem: pip
    directory: /
    labels:
      - "pip"
    open-pull-requests-limit: 100
    schedule:
      interval: daily
      time: "19:45"
      timezone: "Europe/Berlin"
    rebase-strategy: "auto"
