FROM alpine:3.20.2

RUN apk upgrade --no-cache -a && \
    apk add --no-cache python3 \
    py3-pip \
    musl-dev \
    jpeg-dev \
    zlib-dev \
    freetype-dev \
    clang \
    clang-dev \
    llvm \
    m4 \
    cmake \
    python3-dev \
    build-base \
    swig \
    git

ENV VERSION=1.24.9

WORKDIR /tmp

# Erstelle und aktiviere ein virtuelles Umfeld
RUN <<EOF
    pip install --break-system-packages libclang
    wget https://github.com/pymupdf/PyMuPDF/archive/refs/tags/$VERSION.tar.gz
    tar -xvf $VERSION.tar.gz
    cd PyMuPDF-$VERSION
    PYMUPDF_SETUP_MUPDF_TESSERACT=0 python3 setup.py install
    cd ..
    rm -rf PyMuPDF-$VERSION $VERSION.tar.gz  # Clean up
EOF

WORKDIR /

# RUN apk del python3 \
#     py3-pip \
#     musl-dev \
#     jpeg-dev \
#     zlib-dev \
#     freetype-dev \
#     clang \
#     clang-dev \
#     llvm \
#     m4 \
#     cmake \
#     python3-dev \
#     build-base \
#     swig \
#     git
