FROM alpine:3.20.2

RUN apk update && apk add python3 py3-pip py3-wheel musl-dev jpeg-dev zlib-dev freetype-dev clang clang-dev llvm m4 cmake python3-dev build-base swig
# RUN apk update && apk add python3 py3-pip py3-wheel musl-dev jpeg-dev zlib-dev freetype-dev clang clang-dev llvm m4 cmake python3-dev build-base swig

ENV VERSION=1.24.9

WORKDIR /tmp

RUN <<EOF
  pip install --break-system-packages libclang
  wget https://github.com/pymupdf/PyMuPDF/archive/refs/tags/$VERSION.tar.gz
  tar -xvf $VERSION.tar.gz
  cd PyMuPDF-$VERSION
  PYMUPDF_SETUP_MUPDF_TESSERACT=0 python3 setup.py install
EOF

RUN apk del python3 py3-pip py3-wheel musl-dev jpeg-dev zlib-dev freetype-dev clang clang-dev llvm m4 cmake python3-dev build-base swig

WORKDIR /
