name: Deploy Javadoc

env:
  PIP_CACHE_DIR: .pip # Configure the PIP cache directory
  DOCUMENTATIONS_BRANCH: test_java # Configure the documentations branch, which you will use for Github pages

permissions:
  contents: write
  packages: write
  actions: read

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build-push:
    name: "Build & Push docs"
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Cache dependencies for faster build time in future
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./.pip
          key: ${{ runner.os }}-modules-${{ hashFiles('./mkdocs-pip.txt') }}

      # Install dependencies for build process
      - name: Install build dependencies
        run: |
          pip install -IU -r mkdocs-pip.txt

      # Build docs
      - name: Build documentations
        run: |
          mkdocs build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update files
          committer: GitHub Action <action@github.com>
          author: GitHub Action <action@github.com>
          signoff: true
          branch: test_java
          # base: main
          title: "🔨 Update files by <github-actions[bot]>"
          body: |
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            wait
            in progress
            bot
          draft: false
          delete-branch: true
